const fs = require("fs");
const path = require("path");

function exportArtifacts(config, workbook, format) {
  fs.mkdirSync(config.outputCodeDir, { recursive: true });
  fs.mkdirSync(config.outputDataDir, { recursive: true });

  cleanDirectory(config.outputCodeDir, [".meta"]);
  cleanDirectory(config.outputDataDir, [".meta"]);

  for (const enumEntry of workbook.enums) {
    writeFile(path.join(config.outputCodeDir, `${enumEntry.name}.cs`), generateEnumCode(config.namespace, enumEntry));
  }

  for (const table of workbook.tables) {
    writeFile(path.join(config.outputCodeDir, `${table.rowName}.cs`), generateRowCode(config.namespace, table));
    writeFile(path.join(config.outputCodeDir, `${table.name}.cs`), generateTableCode(config.namespace, table));
    writeTableData(config, table, format);
  }

  writeFile(path.join(config.outputCodeDir, `Tables.cs`), generateTablesCode(config.namespace, workbook.tables));
}

function cleanDirectory(directoryPath, keepExtensions) {
  if (!fs.existsSync(directoryPath)) {
    return;
  }
  for (const entry of fs.readdirSync(directoryPath)) {
    const fullPath = path.join(directoryPath, entry);
    const stat = fs.statSync(fullPath);
    if (stat.isDirectory()) {
      continue;
    }
    const extension = path.extname(entry);
    if (keepExtensions.includes(extension)) {
      continue;
    }
    fs.unlinkSync(fullPath);
  }
}

function generateEnumCode(namespaceName, enumEntry) {
  const lines = [];
  lines.push("// <auto-generated>");
  lines.push("");
  lines.push(`namespace ${namespaceName}`);
  lines.push("{");
  lines.push(`    public enum ${enumEntry.name}`);
  lines.push("    {");
  for (const item of enumEntry.items) {
    if (item.comment) {
      lines.push("        /// <summary>");
      lines.push(`        /// ${escapeXml(item.comment)}`);
      lines.push("        /// </summary>");
    }
    lines.push(`        ${item.name} = ${item.value},`);
  }
  lines.push("    }");
  lines.push("}");
  lines.push("");
  return lines.join("\n");
}

function generateRowCode(namespaceName, table) {
  const lines = [];
  lines.push("// <auto-generated>");
  lines.push("");
  lines.push("using System.Collections.Generic;");
  lines.push("using Newtonsoft.Json;");
  lines.push("");
  lines.push(`namespace ${namespaceName}`);
  lines.push("{");
  lines.push(`    public sealed class ${table.rowName}`);
  lines.push("    {");
  for (const field of table.fields) {
    if (field.comment) {
      lines.push("        /// <summary>");
      lines.push(`        /// ${escapeXml(field.comment)}`);
      lines.push("        /// </summary>");
    }
    lines.push(`        [JsonProperty("${field.originalName}")]`);
    lines.push(`        public ${toCSharpType(field.type)} ${field.propertyName} { get; set; }`);
    lines.push("");
  }
  lines.push(`        public static ${table.rowName} ReadFrom(System.IO.BinaryReader reader)`);
  lines.push("        {");
  lines.push(`            return new ${table.rowName}`);
  lines.push("            {");
  for (const field of table.fields) {
    lines.push(`                ${field.propertyName} = ${buildBinaryReadExpression(field.type)},`);
  }
  lines.push("            };");
  lines.push("        }");
  lines.push("");
  lines.push("    }");
  lines.push("}");
  lines.push("");
  return lines.join("\n");
}

function generateTableCode(namespaceName, table) {
  const idProperty = table.idField.propertyName;
  const idType = toCSharpType(table.idField.type);
  const lines = [];
  lines.push("// <auto-generated>");
  lines.push("");
  lines.push("using System.Collections.Generic;");
  lines.push("using System.Linq;");
  lines.push("");
  lines.push(`namespace ${namespaceName}`);
  lines.push("{");
  lines.push(`    public sealed class ${table.name}`);
  lines.push("    {");
  lines.push(`        private readonly Dictionary<${idType}, ${table.rowName}> _dataMap;`);
  lines.push(`        private readonly List<${table.rowName}> _dataList;`);
  for (const indexField of table.indexes) {
    lines.push(`        private readonly Dictionary<${toCSharpType(indexField.type)}, ${table.rowName}> _${toCamelCase(indexField.propertyName)}Index;`);
  }
  lines.push("");
  lines.push(`        public ${table.name}(IEnumerable<${table.rowName}> rows)`);
  lines.push("        {");
  lines.push(`            _dataList = rows?.ToList() ?? new List<${table.rowName}>();`);
  lines.push(`            _dataMap = _dataList.ToDictionary(row => row.${idProperty});`);
  for (const indexField of table.indexes) {
    lines.push(`            _${toCamelCase(indexField.propertyName)}Index = _dataList.ToDictionary(row => row.${indexField.propertyName});`);
  }
  lines.push("        }");
  lines.push("");
  lines.push(`        public Dictionary<${idType}, ${table.rowName}> DataMap => _dataMap;`);
  lines.push(`        public List<${table.rowName}> DataList => _dataList;`);
  lines.push("");
  lines.push(`        public ${table.rowName} Get(${idType} key) => _dataMap[key];`);
  lines.push(`        public ${table.rowName} GetOrDefault(${idType} key) => _dataMap.TryGetValue(key, out var value) ? value : null;`);
  lines.push(`        public bool TryGet(${idType} key, out ${table.rowName} value) => _dataMap.TryGetValue(key, out value);`);
  lines.push(`        public ${table.rowName} this[${idType} key] => _dataMap[key];`);
  for (const indexField of table.indexes) {
    const indexType = toCSharpType(indexField.type);
    const camelName = toCamelCase(indexField.propertyName);
    lines.push("");
    lines.push(`        public ${table.rowName} GetBy${indexField.propertyName}(${indexType} key) => _${camelName}Index[key];`);
    lines.push(`        public ${table.rowName} GetBy${indexField.propertyName}OrDefault(${indexType} key) => _${camelName}Index.TryGetValue(key, out var value) ? value : null;`);
    lines.push(`        public bool TryGetBy${indexField.propertyName}(${indexType} key, out ${table.rowName} value) => _${camelName}Index.TryGetValue(key, out value);`);
  }
  lines.push("    }");
  lines.push("}");
  lines.push("");
  return lines.join("\n");
}

function generateTablesCode(namespaceName, tables) {
  const lines = [];
  lines.push("// <auto-generated>");
  lines.push("");
  lines.push("using System.Collections.Generic;");
  lines.push("using System.IO;");
  lines.push("using Newtonsoft.Json;");
  lines.push("using UnityEngine;");
  lines.push("");
  lines.push(`namespace ${namespaceName}`);
  lines.push("{");
  lines.push("    public sealed class Tables");
  lines.push("    {");
  for (const table of tables) {
    lines.push(`        public ${table.name} ${table.name} { get; }`);
  }
  lines.push("");
  lines.push("        private Tables()");
  lines.push("        {");
  for (const table of tables) {
    lines.push(`            ${table.name} = new ${table.name}(LoadRows("${table.name}", ${table.rowName}.ReadFrom));`);
  }
  lines.push("        }");
  lines.push("");
  lines.push("        public static Tables Load()");
  lines.push("        {");
  lines.push("            return new Tables();");
  lines.push("        }");
  lines.push("");
  lines.push("        private static readonly byte[] BinaryMagic = { 0x46, 0x43, 0x46, 0x47 };");
  lines.push("");
  lines.push("        private static List<T> LoadRows<T>(string tableName, System.Func<BinaryReader, T> readBinaryRow)");
  lines.push("        {");
  lines.push('            var asset = Resources.Load<TextAsset>($"Config/{tableName}");');
  lines.push("            if (asset == null)");
  lines.push("            {");
  lines.push('                throw new FileNotFoundException($"Missing config resource: Config/{tableName}");');
  lines.push("            }");
  lines.push("");
  lines.push("            if (IsBinaryConfig(asset.bytes))");
  lines.push("            {");
  lines.push("                return LoadBinaryRows(asset.bytes, readBinaryRow);");
  lines.push("            }");
  lines.push("");
  lines.push("            var rows = JsonConvert.DeserializeObject<List<T>>(asset.text);");
  lines.push("            return rows ?? new List<T>();");
  lines.push("        }");
  lines.push("");
  lines.push("        private static bool IsBinaryConfig(byte[] bytes)");
  lines.push("        {");
  lines.push("            return bytes != null");
  lines.push("                && bytes.Length >= BinaryMagic.Length");
  lines.push("                && bytes[0] == BinaryMagic[0]");
  lines.push("                && bytes[1] == BinaryMagic[1]");
  lines.push("                && bytes[2] == BinaryMagic[2]");
  lines.push("                && bytes[3] == BinaryMagic[3];");
  lines.push("        }");
  lines.push("");
  lines.push("        private static List<T> LoadBinaryRows<T>(byte[] bytes, System.Func<BinaryReader, T> readBinaryRow)");
  lines.push("        {");
  lines.push("            using var stream = new MemoryStream(bytes);");
  lines.push("            using var reader = new BinaryReader(stream);");
  lines.push("");
  lines.push("            reader.ReadBytes(BinaryMagic.Length);");
  lines.push("            int count = reader.ReadInt32();");
  lines.push("            var rows = new List<T>(count);");
  lines.push("            for (int i = 0; i < count; i++)");
  lines.push("            {");
  lines.push("                rows.Add(readBinaryRow(reader));");
  lines.push("            }");
  lines.push("            return rows;");
  lines.push("        }");
  lines.push("");
  lines.push("        public static string ReadString(BinaryReader reader)");
  lines.push("        {");
  lines.push("            int byteCount = reader.ReadInt32();");
  lines.push("            byte[] bytes = reader.ReadBytes(byteCount);");
  lines.push("            return System.Text.Encoding.UTF8.GetString(bytes);");
  lines.push("        }");
  lines.push("");
  lines.push("        public static List<T> ReadArray<T>(BinaryReader reader, System.Func<BinaryReader, T> readItem)");
  lines.push("        {");
  lines.push("            int count = reader.ReadInt32();");
  lines.push("            var items = new List<T>(count);");
  lines.push("            for (int i = 0; i < count; i++)");
  lines.push("            {");
  lines.push("                items.Add(readItem(reader));");
  lines.push("            }");
  lines.push("            return items;");
  lines.push("        }");
  lines.push("    }");
  lines.push("}");
  lines.push("");
  return lines.join("\n");
}

function writeTableData(config, table, format) {
  if (format === "bin") {
    const buffer = buildBinaryTable(table);
    fs.writeFileSync(path.join(config.outputDataDir, `${table.name}.bytes`), buffer);
    return;
  }

  writeFile(path.join(config.outputDataDir, `${table.name}.json`), `${JSON.stringify(table.rows, null, 2)}\n`);
}

function buildBinaryTable(table) {
  const chunks = [];
  const magic = Buffer.from([0x46, 0x43, 0x46, 0x47]);
  chunks.push(magic);
  const count = Buffer.allocUnsafe(4);
  count.writeInt32LE(table.rows.length, 0);
  chunks.push(count);

  for (const row of table.rows) {
    for (const field of table.fields) {
      chunks.push(encodeValue(row[field.originalName], field.type));
    }
  }

  return Buffer.concat(chunks);
}

function encodeValue(value, type) {
  if (type.kind === "array") {
    const list = Array.isArray(value) ? value : [];
    const chunks = [];
    const count = Buffer.allocUnsafe(4);
    count.writeInt32LE(list.length, 0);
    chunks.push(count);
    for (const item of list) {
      chunks.push(encodeValue(item, type.elementType));
    }
    return Buffer.concat(chunks);
  }

  if (type.kind === "primitive") {
    switch (type.primitive) {
      case "int": {
        const buffer = Buffer.allocUnsafe(4);
        buffer.writeInt32LE(Number(value), 0);
        return buffer;
      }
      case "float": {
        const buffer = Buffer.allocUnsafe(4);
        buffer.writeFloatLE(Number(value), 0);
        return buffer;
      }
      case "bool": {
        return Buffer.from([value ? 1 : 0]);
      }
      case "string":
        return encodeString(String(value ?? ""));
      default:
        throw new Error(`Unsupported primitive ${type.primitive}`);
    }
  }

  if (type.kind === "enum") {
    const buffer = Buffer.allocUnsafe(4);
    buffer.writeInt32LE(Number(value), 0);
    return buffer;
  }

  if (type.kind === "ref") {
    if (type.resolvedPrimitive === "string") {
      return encodeString(String(value ?? ""));
    }
    const buffer = Buffer.allocUnsafe(4);
    buffer.writeInt32LE(Number(value), 0);
    return buffer;
  }

  throw new Error(`Unsupported type kind ${type.kind}`);
}

function encodeString(value) {
  const stringBuffer = Buffer.from(String(value), "utf8");
  const lengthBuffer = Buffer.allocUnsafe(4);
  lengthBuffer.writeInt32LE(stringBuffer.length, 0);
  return Buffer.concat([lengthBuffer, stringBuffer]);
}

function buildBinaryReadExpression(type) {
  if (type.kind === "array") {
    return `Tables.ReadArray(reader, rowReader => ${buildBinaryReadExpressionForNested(type.elementType, "rowReader")})`;
  }

  return buildBinaryReadExpressionForNested(type, "reader");
}

function buildBinaryReadExpressionForNested(type, readerName) {
  if (type.kind === "primitive") {
    switch (type.primitive) {
      case "int":
        return `${readerName}.ReadInt32()`;
      case "float":
        return `${readerName}.ReadSingle()`;
      case "bool":
        return `${readerName}.ReadBoolean()`;
      case "string":
        return `Tables.ReadString(${readerName})`;
      default:
        throw new Error(`Unsupported primitive ${type.primitive}`);
    }
  }

  if (type.kind === "enum") {
    return `(${type.enumName})${readerName}.ReadInt32()`;
  }

  if (type.kind === "ref") {
    return type.resolvedPrimitive === "string" ? `Tables.ReadString(${readerName})` : `${readerName}.ReadInt32()`;
  }

  if (type.kind === "array") {
    return `Tables.ReadArray(${readerName}, rowReader => ${buildBinaryReadExpressionForNested(type.elementType, "rowReader")})`;
  }

  throw new Error(`Unsupported type kind ${type.kind}`);
}

function toCSharpType(type) {
  if (type.kind === "array") {
    return `List<${toCSharpType(type.elementType)}>`;
  }
  if (type.kind === "primitive") {
    switch (type.primitive) {
      case "int":
        return "int";
      case "float":
        return "float";
      case "string":
        return "string";
      case "bool":
        return "bool";
      default:
        throw new Error(`Unsupported primitive ${type.primitive}`);
    }
  }
  if (type.kind === "enum") {
    return type.enumName;
  }
  if (type.kind === "ref") {
    return type.resolvedPrimitive === "string" ? "string" : "int";
  }
  throw new Error(`Unsupported type kind ${type.kind}`);
}

function toCamelCase(value) {
  return value.charAt(0).toLowerCase() + value.slice(1);
}

function escapeXml(value) {
  return String(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

function writeFile(filePath, content) {
  fs.writeFileSync(filePath, content, "utf8");
}

module.exports = {
  exportArtifacts
};
